# Generated by Django 3.2.4 on 2021-06-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=55)),
                ('ciudad', models.CharField(max_length=25)),
            ],
        ),
    ]
